export const buildAxiosGetResponse = ({
    data,
    status,
    statusText,
}) => ({
    data,
    status,
    statusText,
    headers: {
        'access-control-allow-origin': '*',
        'content-length': '95',
        'content-type': 'application/json; charset=utf-8',
        date: 'Tue, 17 Aug 2021 03:22:49 GMT',
        etag: 'W/"5f-886sHH9VUAn0hUMPzRHrC7O0bCE"',
        vary: 'Accept-Encoding',
        'x-powered-by': 'Express',
    },
    config: {
        url: '/apiKey/ny_times',
        method: 'get',
        headers: { Accept: 'application/json, text/plain, */*' },
        transformRequest: [null],
        transformResponse: [null],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        maxBodyLength: -1,
    },
    request: {},
});

export const buildAxiosPostResponse = ({
    data,
    status,
    statusText,
}) => ({
    data,
    status,
    statusText,
    headers: {
        'access-control-allow-origin': '*',
        connection: 'close',
        'content-length': '19',
        'content-type': 'text/html; charset=utf-8',
        date: 'Tue, 17 Aug 2021 03:44:02 GMT',
        etag: 'W/"13-8HaYBUtLIneDNwJU85BxMWtLOzo"',
        vary: 'Accept-Encoding',
        'x-powered-by': 'Express',
    },
    config: {
        url: '/movie/create/The Lost Leonardo',
        method: 'post',
        headers: { Accept: 'application/json, text/plain, */*' },
        transformRequest: [null],
        transformResponse: [null],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        maxBodyLength: -1,
    },
    request: {},
});
